name: DolDoc.NET
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results-3.1
          path: TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

